server:
  port: 8080

spring:

  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp

  rabbitmq:
    host: localhost
    port: 3131
    username: guest
    password: guest

  cloud:
    stream:
      default:
        contentType: application/json