server:
  port: 0
spring:
  datasource:
    url: jdbc:postgresql://localhost/skytask
    username: postgres
    password: postgres
    generate-ddl: true

  rabbitmq:
    host: localhost
    port: 3131
    username: guest
    password: guest
